behaviors:
  DrownMouse:
    trainer_type: ppo
    hyperparameters:
        batch_size: 2560
        beta: 5.0e-2
        buffer_size: 409600
        epsilon: 0.2
        lambd: 0.95
        learning_rate: 3.0e-5
        learning_rate_schedule: linear
        num_epoch: 5
    network_settings:
        hidden_units: 512
        normalize: false
        num_layers: 2
        use_recurrent: false
        memory_size: 128
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: .99
    time_horizon: 2048
    summary_freq: 50000
    max_steps: 36e7