behaviors:
  PositionGuesser:
    trainer_type: ppo
    hyperparameters:
        batch_size: 2560
        beta: 5.0e-3
        buffer_size: 409600
        epsilon: 0.2
        lambd: 0.95
        learning_rate: 3.0e-4
        learning_rate_schedule: linear
        num_epoch: 3
    network_settings:
        normalize: false
        num_layers: 2
        use_recurrent: false
        memory_size: 128
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
    time_horizon: 2048
    summary_freq: 10000
    max_steps: 1e7
